"""
/***************************************************************************
 ETLConnector4ODK
                                 A QGIS plugin
 Plugin for extraction, transformation and loading data from ODK server to QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-03
        copyright            : (C) 2022 by Derrick Demeveng
        email                : demeveng@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):
  from .mainPlugin import FetchDataPlugin
  return FetchDataPlugin(iface)

# any other initialisation needed